sudo: required
before_install: # if "install" is overridden
# Repo for Yarn
 curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
language: node_js
node_js:
  - "11.3.0"
cache:
  directories:
  - node_modules
script:
  - yarn test
  - yarn run build
